#!/bin/bash

source ~/.config/bash/alias.bash
source ~/.config/bash/colors.bash
source ~/.config/bash/git.bash # Needed for the prompt
source ~/.config/bash/prompt.bash
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Set the editor and git editor
export EDITOR=nvim

# Set the vi mode for bash
set -o vi

# Unbreak broken, non-colored terminal
alias ls='ls -G'
alias ll='ls -lG'
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"

# Erase duplicates in history
export HISTCONTROL=erasedups
# Store 10k history entries
export HISTSIZE=10000
# Append to the history file when exiting instead of overwriting it
shopt -s histappend

# Add home directory binaries to PATH
export PATH="~/bin:$PATH"
