#!/bin/bash

source ~/.config/bash/alias.bash
source ~/.config/bash/colors.bash
source ~/.config/bash/git.bash # Needed for the prompt
source ~/.config/bash/prompt.bash
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Set the editor and git editor
export EDITOR=nvim
export GIT_EDITOR=nvim

# Set the vi mode for bash
set -o vi
